### PR TITLE
Fix #226 by restricting the cache directory path to contain only alphanumeric plus the few shell-benign special characters

### LINKED ISSUE #226: remote shell commands: need to watch out for special characters
I have a non-reproducible case , where sjef has a problem with commands sent to the remote backend, when e.g. the cache
contains special characters.

I have created a backend with:

```
    <backend name="withquestionmark"
             host="doll@XXX.XX.XX.XXX"
             cache="/SCR1/doll/a?"
             run_command="molpro {-n %n:1} {-m %m:100m} {-t %t}  {-G %G} "/>
    <backend name="withstar"
             host="doll@XXX.XX.XX.XXX"
             cache="/SCR1/doll/a*"
             run_command="molpro {-n %n:1} {-m %m:100m} {-t %t}  {-G %G} "/>
```

Logged in on the remote machine, I lclean up:
`rm -r /SCR1/doll/a*`
and then create:

```
mkdir /SCR1/doll/a*
mkdir /SCR1/doll/a\?
mkdir /SCR1/doll/a2
```

Note that already these commands are somewhat ambiguous. If you create first
`mkdir /SCR1/doll/a2`

then

`mkdir /SCR1/doll/a*`

fails with:

`mkdir /SCR1/doll/a*
mkdir: cannot create directory ‘/SCR1/doll/a*’: File exists`

When I now run an input, I obtain non-reproducibly (Molpro input file is irrelevant):

```
sjef run -b withquestionmark -f ~/Documents/molpro/test-remote-shell.molpro
Job number: 11130
```

and on the remote machine I have:
```

ls -ltR --time-style="+%Y-%m-%d %H:%M:%S" a?
a2:
total 0
drwxr-xr-x 2 doll user 130 2022-10-10 09:22:32 16634613613130276360

a2/16634613613130276360:
total 12
-rw-r--r-- 1 doll user 106 2022-10-10 09:22:32 1.inp
-rw-r--r-- 1 doll user   0 2022-10-10 09:22:32 1.lock
-rw-r--r-- 1 doll user  25 2022-10-10 09:22:32 molpro.rc
-rw-r--r-- 1 doll user 200 2022-10-10 09:22:32 sext.xyz

a?:
total 0
drwxr-xr-x 2 doll user 50 2022-10-10 09:22:33 16634613613130276360

a?/16634613613130276360:
total 8
-rw-r--r-- 1 doll user 227 2022-10-10 09:22:33 1.stderr
-rw-r--r-- 1 doll user  91 2022-10-10 09:22:33 1.stdout

a*:
total 0

```

So the files were rsync-ed to /SCR1/doll/a2/16634613613130276360 , and the calculation was run in

/SCR1/doll/a?/16634613613130276360

Sometimes I have this problem with backends such as withstar  , withquestionmark . For a backend without special characters,
it works reproducibly.

It is vaguely related to  https://github.com/molpro/sjef/issues/59   . One could work around this by having
extra ' ' , but this depends on the shell which we do not know.

### PR DESCRIPTION
**Pull request by pjknowles**
Fixes #226

### CODE REVIEW

**Comment by klauspdoll** [comment]
Yes, this looks fairly safe now. Maybe just go ahead and merge, and I will try it out.

**Comment by pjknowles** [comment]
> Yes, this looks fairly safe now. Maybe just go ahead and merge, and I will try it out.

And the restriction on the path name is not too restrictive? I got the idea that it might be impossible or inconvenient to constrain the location of the project bundle not to have a space in the path (eg a cloud directory), but that for the remote cache it should be possible to place it somewhere without a space.

**Comment by pjknowles** [comment]
Should extend the C binding to catch the exception of a bad remote cache directory, and send back a return code.

**Comment by klauspdoll** [comment]
Yes, it couid be too restrictive .... I just don't know .... E.g. as you wrote some time ago, your university cloud storage synchorises to a directory with blanks .... unfortunately, blanks in filenames have become popular...

**Comment by pjknowles** [comment]
> Yes, it couid be too restrictive .... I just don't know .... E.g. as you wrote some time ago, your university cloud storage synchorises to a directory with blanks .... unfortunately, blanks in filenames have become popular...


Yes, for the project directory permanent location, but the cache could be anywhere on the remote machine that the user can write, so I thought it's unlikely that would have to contain a space or special character. But maybe it's possible that it would have to be based on a username that happened to contain an umlaut or similar. Probably this can be accommodated by changing a-z to a regex for all letters - I'll try.

**Comment by pjknowles** [comment]
> Should extend the C binding to catch the exception of a bad remote cache directory, and send back a return code.

Actually it already does this ... prints error message then returns failure.

**Pull request merged**
